CREATE TABLE [identity].[identities]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[UserId] BIGINT NOT NULL FOREIGN KEY REFERENCES [identity].[users](Id) ON DELETE CASCADE,
	[Name] NVARCHAR(256) NOT NULL,
	[Default] BIT NOT NULL,
	[Deleted] BIT NOT NULL DEFAULT 0
)
