CREATE TABLE [identity].[sessions]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[UserId] BIGINT NOT NULL FOREIGN KEY REFERENCES [identity].[users](Id) ON DELETE CASCADE,
	[Token] CHAR(128) NOT NULL,
	[CreatedAt] DATETIMEOFFSET NOT NULL,
	[ExpiresAt] DATETIMEOFFSET NOT NULL
)
