CREATE TABLE [identity].[sessions]
(
	[Id] BIGINT NOT NULL PRIMARY KEY,
	[UserId] BIGINT NOT NULL REFERENCES [identity].[users](Id) ON DELETE CASCADE,
	[Token] VARCHAR(512) NOT NULL,
	[CreatedAt] DATETIMEOFFSET NOT NULL,
	[ExpiresAt] DATETIMEOFFSET NOT NULL
)
